# Generated by Django 6.0.6 on 2026-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_consultancynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
