# Generated by Codex on 2026-07-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('authentication', '0006_consultancyvisitnotification')]

    operations = [
        migrations.CreateModel(
            name='ConsultancyCountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('documents', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['country']},
        ),
        migrations.AddConstraint(
            model_name='consultancycountryprofile',
            constraint=models.UniqueConstraint(fields=('consultancy', 'country'), name='unique_consultancy_country_profile'),
        ),
    ]
