# Generated by Django 6.0.6 on 2026-07-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_consultancycountryprofile'),
        ('authentication', '0010_alter_consultancynotification_id_and_more'),
    ]

    operations = [
    ]
