"""
app/services/ai_detector.py
Detects whether a cover letter or SOP was AI-generated
using Gemini with a specialized auditor prompt.
Returns confidence_score (0-100%) with detailed signatures.
"""
import json
import os
import re

import google.generativeai as genai
from fastapi import HTTPException

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

SYSTEM_PROMPT = """You are an expert document auditor specializing in identifying text generated by Large Language Models (LLMs) like ChatGPT, Claude, and Gemini. You are analyzing Statements of Purpose (SOPs) and Cover Letters.

Analyze the provided text for the following AI-generation signatures:
1. "AI Clichés": Overuse of transitional phrases and words like "delve," "testament," "beacon," "foster," "in conclusion," "furthermore," "not only... but also," "passionate about," "dynamic landscape."
2. Structural Rigidity: Exactly 4-5 paragraphs, highly uniform paragraph lengths, and perfectly parallel sentence structures.
3. Low Information Density: A lot of beautifully written words that say very little concrete or specific about the applicant's unique experiences.
4. "The AI Pivot": The classic transition where it shifts from a generic philosophical hook to "My journey began when..."

You must return a raw JSON object with NO markdown, NO backticks, NO explanation outside the JSON:
{
  "is_ai_generated": true or false,
  "confidence_score": number between 0 and 100,
  "detected_signatures": ["specific red flags found"],
  "human_elements": ["specific human details found if any"]
}"""


def _extract_json(raw: str) -> dict:
    """Strip markdown fences if Gemini wraps response despite instructions."""
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw.strip(), flags=re.MULTILINE)
    return json.loads(cleaned)


def detect_ai_content(text: str) -> dict:
    """
    Sends document to Gemini AI auditor.
    Returns confidence_score (0-100) + verdict + detected signatures.
    """
    if not GEMINI_API_KEY:
        # Return a safe fallback instead of crashing the whole pipeline
        return {
            "is_ai_generated": False,
            "confidence_score": 0,
            "verdict": "AI detection unavailable — GEMINI_API_KEY not configured",
            "risk_level": "None",
            "detected_signatures": [],
            "human_elements": [],
        }

    try:
        model = genai.GenerativeModel(
            "gemini-2.5-flash",
            system_instruction=SYSTEM_PROMPT,
            generation_config={"response_mime_type": "application/json"},
        )
        response = model.generate_content(
            f"Analyze this document for AI generation:\n\n{text[:3000]}"
            # Limit to 3000 chars to save tokens — enough for detection
        )
        result = _extract_json(response.text)

        # Add human-readable verdict based on confidence score
        score = result.get("confidence_score", 0)
        if score >= 75:
            verdict = "Very likely AI-generated"
            risk = "High"
        elif score >= 50:
            verdict = "Possibly AI-assisted"
            risk = "Medium"
        elif score >= 25:
            verdict = "Mostly human-written"
            risk = "Low"
        else:
            verdict = "Human-written"
            risk = "None"

        result["verdict"] = verdict
        result["risk_level"] = risk
        return result

    except json.JSONDecodeError:
        return {
            "is_ai_generated": False,
            "confidence_score": 0,
            "verdict": "AI detection could not parse response — retry",
            "risk_level": "None",
            "detected_signatures": [],
            "human_elements": [],
        }
    except Exception as exc:
        return {
            "is_ai_generated": False,
            "confidence_score": 0,
            "verdict": f"AI detection failed: {str(exc)[:100]}",
            "risk_level": "None",
            "detected_signatures": [],
            "human_elements": [],
        }