"""
app/services/ai_detector.py
Detects whether a cover letter or SOP was AI-generated
using Gemini with a specialized auditor prompt.
"""
import json
import os
import re

try:
    import google.generativeai as genai
except Exception:  # pragma: no cover - fallback for unsupported runtimes
    genai = None

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY and genai is not None:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
    except Exception:
        pass

SYSTEM_PROMPT = """You are an expert document auditor specializing in identifying text generated by Large Language Models (LLMs) like ChatGPT, Claude, and Gemini. You are analyzing Statements of Purpose (SOPs) and Cover Letters.

Analyze the provided text for the following AI-generation signatures:
1. "AI Clichés": Overuse of transitional phrases and words like "delve," "testament," "beacon," "foster," "in conclusion," "furthermore," "not only... but also," "passionate about," "dynamic landscape."
2. Structural Rigidity: Exactly 4-5 paragraphs, highly uniform paragraph lengths, and perfectly parallel sentence structures (e.g., every sentence starting with "By doing X, I learned Y").
3. Low Information Density: A lot of beautifully written words that say very little concrete or specific about the applicant's unique, messy human experiences.
4. "The AI Pivot": The classic transition in paragraph 2 or 3 where it shifts from a generic philosophical hook to "My journey began when..."

You must return a raw JSON object. Do not include any conversational text, markdown formatting blocks (like ```json), or explanations outside the JSON structure.

The JSON structure must be exactly:
{
  "is_ai_generated": true/false,
  "confidence_score": 0 to 100,
  "detected_signatures": [
    "List specific red flags found, e.g., Overuse of words like delve and testament",
    "Perfectly symmetrical paragraph lengths indicating structural rigidity"
  ],
  "human_elements": [
    "List specific, idiosyncratic details that suggest human writing, if any, e.g., Highly specific naming of a niche lab instrument"
  ]
}"""


def _extract_json(raw: str) -> dict:
    """Strip markdown fences if Gemini wraps response despite instructions."""
    cleaned = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw.strip(), flags=re.MULTILINE)
    return json.loads(cleaned)


def detect_ai_content(text: str) -> dict:
    """
    Sends the document to Gemini for AI detection analysis.
    Returns structured result with confidence score and detected signatures.
    Falls back to a safe placeholder result if the detector is unavailable.
    """
    if not GEMINI_API_KEY or genai is None:
        return {
            "is_ai_generated": None,
            "confidence_score": 0,
            "detected_signatures": [],
            "human_elements": [],
            "verdict": "Unable to evaluate",
            "risk_level": "Unknown",
            "error": "GEMINI_API_KEY is not configured or the Gemini client is unavailable.",
        }

    try:
        model = genai.GenerativeModel(
            "gemini-2.5-flash",
            system_instruction=SYSTEM_PROMPT,
            generation_config={"response_mime_type": "application/json"},
        )
        response = model.generate_content(
            f"Analyze this document for AI generation:\n\n{text}"
        )
        result = _extract_json(response.text)

        score = result.get("confidence_score", 0)
        if score >= 75:
            verdict = "Very likely AI-generated"
            risk = "High"
        elif score >= 50:
            verdict = "Possibly AI-assisted"
            risk = "Medium"
        elif score >= 25:
            verdict = "Mostly human-written"
            risk = "Low"
        else:
            verdict = "Human-written"
            risk = "None"

        result["verdict"] = verdict
        result["risk_level"] = risk
        return result

    except json.JSONDecodeError:
        return {
            "is_ai_generated": None,
            "confidence_score": 0,
            "detected_signatures": [],
            "human_elements": [],
            "verdict": "Unable to evaluate",
            "risk_level": "Unknown",
            "error": "AI detector returned invalid JSON.",
        }
    except Exception as exc:
        return {
            "is_ai_generated": None,
            "confidence_score": 0,
            "detected_signatures": [],
            "human_elements": [],
            "verdict": "Unable to evaluate",
            "risk_level": "Unknown",
            "error": f"AI detection failed: {exc}",
        }